
// default
//#define MUMAN_MESSAGE_STRING 1 
//#define MUMAN_MESSAGE_INT 2

#define RAFT_VOTE_MESSAGE 1
#define RAFT_VOTE_MESSAGE_OK 2

#define RAFT_APPEND_ENTRY_MESSAGE 3
#define RAFT_APPEND_ENTRY_MESSAGE_OK 4
#define RAFT_APPEND_ENTRY_MESSAGE_ERROR 5

#define RAFT_HEARTBEAT_MSSAGE 5

#define ECHO_MESSAGE 65534
#define BLANK_MESSAGE 65535

